Repository skpandey885/HealhUb, pull requests merged in 2022-02, with the labels that each got.

#23 update privacy policy
  pages/about.html
Labels: JWOC, easy

#18 Made Responsive Table for Covid Data and Improved Stats
  css/covidSection.css
  js/covidSecion.js
Labels: JWOC, Medium

#26 Improved the css of the website
  css/covidSection.css
  pages/covidSection.html
Labels: JWOC, Medium

#38 About
  pages/about.html
Labels: JWOC, easy

#40 I added Tools section in navbar and created Tools page as per the issue #25
  assets/tools_bmi.jpg
  assets/tools_head.jpg
  assets/tools_hospitals.jpg
  assets/tools_medicalhelp.jpg
  css/tools.css
  index.html
  js/tools.js
  pages/about.html
  pages/bmi.html
  pages/cards.html
  pages/covidBlogs.html
  pages/covidSection.html
  pages/team-members.html
  pages/tips.html
  pages/tools.html
Labels: JWOC, Medium

#46 Added Do's & Dont's in different boxes and styled them
  css/covidSection.css
  pages/covidSection.html
Labels: JWOC, easy

#43 Modified CSS of Teams Page
  assets/nature.jpg
  css/team-members.css
  pages/team-members.html
Labels: JWOC, Medium

#48 Preloader added
  css/homepage.css
  index.html
Labels: JWOC, Medium

#58 #55 - Improved the responsiveness of the Preloader
  css/homepage.css
  index.html
Labels: JWOC, Medium

#57 Fixed the design on navbar in tools page
  css/tools.css
  pages/tips.html
  pages/tools.html
Labels: JWOC, easy

#49 #30/change navbar design
  css/covidSection.css
  pages/covidSection.html
Labels: JWOC, easy

#68 #59 Added slide down animation
  css/homepage.css
  index.html
Labels: JWOC, Medium

#74 Created Medical Help Page along with some CSS.
  assets/mediclHelp.jpg
  css/medicalHelp.css
  js/medicalHelp.js
  pages/medicalHelp.html
  pages/tools.html
Labels: JWOC, Medium

#84 Tools Page Responsiveness
  css/tools.css
  pages/tools.html
Labels: JWOC, Medium

#86 Trainer
  assets/age.svg
  assets/arrow-down.svg
  assets/bench.jpg
  assets/crunch.jpg
  assets/cyoga.jpg
  assets/deadlift.jpg
  assets/goal.svg
  assets/incline.jpg
  assets/jump-girl.svg
  assets/jumpjack.jpg
  assets/jumpjack.webp
  assets/leg.jpg
  assets/lunges.jpg
  assets/mresist.jpg
  assets/mwalking.jpg
  assets/myoga.jpg
  assets/plank.jpg
  assets/plank.png
  assets/prod.svg
  assets/pullup.jpg
  assets/pushup.jpg
  assets/resist.jpg
  assets/result.svg
  assets/run-boy.svg
  assets/run-girl.svg
  assets/side.jpg
  assets/squat.jpg
  assets/teen-loss.jpg
  assets/trainer.svg
  assets/walking.jpg
  assets/wave-down.svg
  assets/wave.svg
  css/trainer.css
  js/trainer.js
  pages/tools.html
  pages/trainer.html
Labels: JWOC, Hard

#87 UI redesigned for the Medical Help Page
  assets/TB.jpg
  assets/asthma.jpg
  assets/bullet-icon.svg
  assets/commoncold.jpg
  assets/covid.jpg
  assets/dengue.jpg
  assets/diabetes.jpg
  assets/malaria.jpg
  assets/mediclHelp.jpg
  assets/typhoid.jpg
  css/medicalHelp.css
  js/medicalHelp.js
  pages/medicalHelp.html
  pages/tools.html
Labels: JWOC, Medium
