Repository skpandey885/HealhUb, pull requests merged in 2022-10, with the labels that each got.

#124 added font-awesome scripts for icons in index.html
  index.html
Labels: hacktoberfest-accepted

#128 Updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement, hacktoberfest-accepted

#144 Improved Frontend
  css/about.css
  css/bmi.css
  css/bodyFat.css
  css/calorie.css
  css/cards.css
  css/covidBlogs.css
  css/covidSection.css
  css/homepage.css
  css/hospitals.css
  css/medicalHelp.css
  css/team-members.css
  css/tips.css
  css/tools.css
  css/trainer.css
  index.html
  js/bmi.js
  pages/about.html
  pages/bmi.html
  pages/bodyFat.html
  pages/calorie.html
  pages/cards.html
  pages/covidBlogs.html
  pages/covidSection.html
  pages/hospitals.html
  pages/medicalHelp.html
  pages/team-members.html
  pages/tips.html
  pages/tools.html
  pages/trainer.html
Labels: hacktoberfest-accepted

#138 updated issue #130
  css/about.css
Labels: hacktoberfest-accepted

#149 Modified tips page
  assets/tips_bg.jpg
  css/tips.css
  pages/tips.html
Labels: hacktoberfest-accepted

#161 changes in ux and minor changes in ui
  assets/med.jpg
  css/about.css
  js/about.js
  pages/about.html
Labels: hacktoberfest
